import { usePortalSettings } from "../../data/portalSettingsData";
import React, { useState } from "react";
import { useStudents } from "../../data/studentsData";
import { useSessions, TERMS } from "../../data/sessionsData";
import { getStoredScores, ScoreRecord } from "../../data/scoresData";
import { useSkillsDb } from "../../data/skillsData";
import { getStoredPins, saveStoredPins } from "../../data/pinsData";
import { isResultReleased } from "../../data/resultsReleaseData";
import { Card, CardContent, CardHeader, CardTitle, Button, Input, Label } from "@/src/components/ui";
import { Search, Printer, Award, CheckCircle, AlertCircle, FileText, UserCheck, RefreshCw, Key } from "lucide-react";
import { Link } from "react-router-dom";

export default function ResultChecker() {
  const [portalSettings] = usePortalSettings();
  const [students] = useStudents();
  const [sessions, , currentSession] = useSessions();
  const scores = getStoredScores();
  const [skillsDb] = useSkillsDb();

  // Search parameters
  const [studentId, setStudentId] = useState("");
  const [selectedSessionYear, setSelectedSessionYear] = useState(() => currentSession || "2025/2026");
  const [selectedTerm, setSelectedTerm] = useState("First Term");
  const [pinCode, setPinCode] = useState("");

  // Output State
  const [foundStudent, setFoundStudent] = useState<any | null>(null);
  const [studentScores, setStudentScores] = useState<ScoreRecord[]>([]);
  const [hasSearched, setHasSearched] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");

  const targetSession = `${selectedSessionYear} - ${selectedTerm}`;

  const handleCheckResult = (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    setErrorMessage("");
    setIsLoading(true);
    setHasSearched(false);

    setTimeout(() => {
      setIsLoading(false);
      setHasSearched(true);

      const trimmedId = studentId.trim().toUpperCase();
      const trimmedPin = pinCode.trim().toUpperCase();

      if (!trimmedId) {
        setErrorMessage("Please enter a valid Student Admission / Registration Number.");
        setFoundStudent(null);
        return;
      }

      if (!trimmedPin) {
        setErrorMessage("Scratch Card PIN is required. You cannot access results without entering a valid PIN.");
        setFoundStudent(null);
        return;
      }

      if (trimmedPin.length < 4) {
        setErrorMessage("Invalid Scratch Card PIN format. Please check your scratch card and enter a valid PIN code.");
        setFoundStudent(null);
        return;
      }

      // Search student by ID or Name match
      const matchedStudent = students.find(s => 
        s.id.toUpperCase() === trimmedId || 
        s.name.toUpperCase() === trimmedId ||
        s.id.replace(/\//g, "").toUpperCase() === trimmedId.replace(/\//g, "")
      );

      if (!matchedStudent) {
        setErrorMessage(`No student record found matching Registration Number: "${studentId}". Please verify your admission number.`);
        setFoundStudent(null);
        return;
      }

      // Check Scratch Card PIN validity against stored PIN records
      const allPins = getStoredPins();
      const matchedPin = allPins.find(p => 
        p.pinCode.toUpperCase() === trimmedPin || 
        p.pinCode.replace(/-/g, "").toUpperCase() === trimmedPin.replace(/-/g, "")
      );

      if (!matchedPin) {
        setErrorMessage(`Invalid Scratch Card PIN code ("${pinCode}"). Please enter a valid PIN generated by the school admin.`);
        setFoundStudent(null);
        return;
      }

      if (matchedPin.status === "Inactive") {
        setErrorMessage(`This Scratch Card PIN (${matchedPin.pinCode}) is currently INACTIVE. Please contact the school bursar or administrator to activate your PIN.`);
        setFoundStudent(null);
        return;
      }

      if (matchedPin.usesRemaining <= 0 || matchedPin.status === "Expired") {
        setErrorMessage(`This Scratch Card PIN (${matchedPin.pinCode}) has reached its maximum usage limit or expired. Please acquire a new scratch card PIN.`);
        setFoundStudent(null);
        return;
      }

      // Verify PIN student match (or class match if batch generated)
      if (matchedPin.studentId && matchedPin.studentId !== matchedStudent.id && matchedPin.class && matchedPin.class !== matchedStudent.class) {
        setErrorMessage(`Scratch Card PIN (${matchedPin.pinCode}) is assigned to another student/class (${matchedPin.studentName || matchedPin.class}). Please use the correct PIN assigned to ${matchedStudent.name}.`);
        setFoundStudent(null);
        return;
      }

      // Check if Admin has released results for this Session, Term, and Class
      const released = isResultReleased(selectedSessionYear, selectedTerm, matchedStudent.class);
      if (!released) {
        setErrorMessage(`RESULT NOT RELEASED: The examination results for ${selectedSessionYear} - ${selectedTerm} (${matchedStudent.class}) have not been officially published by the school administration yet. Your Scratch Card PIN was not used. Please check back later.`);
        setFoundStudent(null);
        return;
      }

      // Update PIN usage count
      const updatedPins = allPins.map(p => {
        if (p.id === matchedPin.id) {
          const newUses = Math.max(0, p.usesRemaining - 1);
          return {
            ...p,
            usesRemaining: newUses,
            status: (newUses === 0 ? "Used" : "Active") as any,
            lastUsedAt: new Date().toLocaleString()
          };
        }
        return p;
      });
      saveStoredPins(updatedPins);

      // Fetch student's scores for selected session & term
      const matchedScores = scores.filter(sc => 
        sc.studentId === matchedStudent.id && 
        (sc.session === targetSession || sc.session.includes(selectedSessionYear))
      );

      setFoundStudent(matchedStudent);
      setStudentScores(matchedScores);
    }, 400);
  };

  // Calculations
  const totalObtained = studentScores.reduce((acc, curr) => acc + (curr.total || 0), 0);
  const subjectCount = studentScores.length;
  const averagePercentage = subjectCount > 0 ? (totalObtained / subjectCount).toFixed(1) : "0.0";
  const overallGrade = Number(averagePercentage) >= 70 ? "A (Distinction)" : Number(averagePercentage) >= 60 ? "B (Very Good)" : Number(averagePercentage) >= 50 ? "C (Credit)" : "D (Pass)";

  return (
    <div className="min-h-screen bg-slate-50 py-10 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto space-y-8">

        {/* TOP BRAND HEADER */}
        <div className="bg-gradient-to-r from-brand-950 via-slate-900 to-brand-900 text-white rounded-2xl p-6 sm:p-8 shadow-xl relative overflow-hidden print:hidden">
          <div className="absolute right-0 top-0 -mt-8 -mr-8 w-64 h-64 bg-brand-500/10 rounded-full blur-3xl pointer-events-none"></div>
          
          <div className="flex flex-col md:flex-row items-center justify-between gap-6 relative z-10">
            <div className="flex items-center gap-4 text-center md:text-left">
              <div className="w-16 h-16 rounded-2xl bg-white/10 backdrop-blur-md border border-white/20 flex items-center justify-center text-amber-400 shrink-0 shadow-inner">
                <Award size={36} />
              </div>
              <div>
                <span className="inline-block px-3 py-1 rounded-full text-xs font-bold uppercase tracking-widest bg-amber-400/20 text-amber-300 border border-amber-400/30 mb-2">
                  Public Portal Access
                </span>
                <h1 className="text-2xl sm:text-3xl font-extrabold font-heading text-white">
                  Online Student Result Checker
                </h1>
                <p className="text-slate-300 text-sm mt-1 max-w-xl">
                  Official {portalSettings.schoolName} portal. Instantly check, verify, and print academic terminal report sheets for all students.
                </p>
              </div>
            </div>

            <Link to="/login" className="shrink-0">
              <Button variant="outline" className="bg-white/10 hover:bg-white/20 text-white border-white/30 text-xs font-bold gap-2">
                <UserCheck size={16} /> Portal Login
              </Button>
            </Link>
          </div>
        </div>

        {/* INPUT SEARCH FORM */}
        <div className="max-w-2xl mx-auto print:hidden">
          <Card className="border-0 shadow-md bg-white rounded-2xl overflow-hidden">
            <CardHeader className="bg-slate-900 text-white p-5 border-b border-slate-800">
              <CardTitle className="text-base font-bold flex items-center gap-2">
                <Search size={18} className="text-brand-400" />
                Enter Student Assessment & PIN Details
              </CardTitle>
            </CardHeader>

            <CardContent className="p-6 space-y-5">
              <form onSubmit={handleCheckResult} className="space-y-4">
                <div>
                  <Label className="text-slate-700 text-xs font-bold uppercase tracking-wider block mb-1.5">
                    Student Reg / Admission Number <span className="text-rose-500">*</span>
                  </Label>
                  <div className="relative">
                    <Input
                      type="text"
                      placeholder="e.g. ESS/2026/001"
                      className="h-11 pl-10 uppercase font-mono font-semibold text-slate-900 border-slate-300 focus:ring-brand-500"
                      value={studentId}
                      onChange={(e) => setStudentId(e.target.value)}
                      required
                    />
                    <FileText size={18} className="absolute left-3 top-3 text-slate-400 pointer-events-none" />
                  </div>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <Label className="text-slate-700 text-xs font-bold uppercase tracking-wider block mb-1.5">
                      Academic Session <span className="text-rose-500">*</span>
                    </Label>
                    <select
                      className="w-full h-11 rounded-lg border border-slate-300 bg-white px-3 text-sm font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-brand-500"
                      value={selectedSessionYear}
                      onChange={(e) => setSelectedSessionYear(e.target.value)}
                    >
                      {sessions.map(s => (
                        <option key={s} value={s}>{s} Academic Session</option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <Label className="text-slate-700 text-xs font-bold uppercase tracking-wider block mb-1.5">
                      Academic Term <span className="text-rose-500">*</span>
                    </Label>
                    <select
                      className="w-full h-11 rounded-lg border border-slate-300 bg-white px-3 text-sm font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-brand-500"
                      value={selectedTerm}
                      onChange={(e) => setSelectedTerm(e.target.value)}
                    >
                      {TERMS.map(t => (
                        <option key={t} value={t}>{t}</option>
                      ))}
                    </select>
                  </div>
                </div>

                <div>
                  <Label className="text-slate-700 text-xs font-bold uppercase tracking-wider block mb-1.5 flex items-center justify-between">
                    <span>Result Scratch Card PIN <span className="text-rose-500">* (Compulsory)</span></span>
                    <span className="text-[10px] text-amber-700 font-bold uppercase bg-amber-100 px-2 py-0.5 rounded">Required for Access</span>
                  </Label>
                  <div className="relative">
                    <Input
                      type="text"
                      placeholder="Enter Scratch Card PIN (e.g. ESS-PIN-2026-9912)"
                      className="h-11 pl-10 font-mono text-xs border-slate-300 text-slate-900 font-semibold uppercase"
                      value={pinCode}
                      onChange={(e) => setPinCode(e.target.value)}
                      required
                    />
                    <Key size={18} className="absolute left-3 top-3 text-slate-400 pointer-events-none" />
                  </div>
                  <p className="text-[11px] text-slate-500 mt-1">
                    Enter the valid scratch card PIN code provided by the school administration to unlock and view the report sheet.
                  </p>
                </div>

                {errorMessage && (
                  <div className="p-4 bg-rose-50 border border-rose-200 text-rose-800 text-xs rounded-xl flex items-start gap-3 animate-in fade-in">
                    <AlertCircle size={18} className="text-rose-600 shrink-0 mt-0.5" />
                    <div>
                      <p className="font-bold">Result Access Restricted</p>
                      <p className="mt-0.5">{errorMessage}</p>
                    </div>
                  </div>
                )}

                <div className="pt-2 flex flex-col sm:flex-row gap-3">
                  <Button
                    type="submit"
                    variant="brand"
                    disabled={isLoading}
                    className="h-11 flex-1 font-bold gap-2 text-sm shadow-md"
                  >
                    {isLoading ? (
                      <>
                        <RefreshCw size={16} className="animate-spin" /> Verifying Records & PIN...
                      </>
                    ) : (
                      <>
                        <Search size={16} /> Check Result
                      </>
                    )}
                  </Button>

                  <Button
                    type="button"
                    variant="outline"
                    className="h-11 border-slate-300 text-slate-700 hover:bg-slate-100"
                    onClick={() => {
                      setStudentId("");
                      setPinCode("");
                      setFoundStudent(null);
                      setHasSearched(false);
                      setErrorMessage("");
                    }}
                  >
                    Clear Form
                  </Button>
                </div>
              </form>
            </CardContent>
          </Card>
        </div>

        {/* RESULT SHEET DISPLAY AREA */}
        {hasSearched && foundStudent && (
          <div className="space-y-4 animate-in fade-in zoom-in-95 duration-300">
            <div className="flex items-center justify-between bg-white p-4 rounded-xl border border-slate-200 shadow-xs print:hidden">
              <div className="flex items-center gap-2 text-emerald-800 font-bold text-sm">
                <CheckCircle size={18} className="text-emerald-600" />
                <span>Result record successfully retrieved for {foundStudent.name}</span>
              </div>
              <Button
                variant="outline"
                size="sm"
                className="bg-brand-900 text-white hover:bg-brand-800 font-bold gap-2"
                onClick={() => window.print()}
              >
                <Printer size={16} /> Print Official Result Slip
              </Button>
            </div>

            {/* OFFICIAL REPORT CARD SHEET */}
            <div className="bg-white p-6 sm:p-10 rounded-2xl shadow-xl border border-slate-200 text-slate-900 space-y-6 print:shadow-none print:border-none print:p-0">
              
              {/* SCHOOL LETTERHEAD HEADER */}
              <div className="border-b-2 border-slate-900 pb-5">
                <div className="flex flex-col sm:flex-row items-center justify-between gap-4 text-center sm:text-left">
                  <div className="flex items-center gap-4">
                    <div className="w-20 h-20 bg-brand-900 text-amber-400 rounded-xl flex items-center justify-center font-black text-2xl border-2 border-amber-400 shrink-0 shadow-md overflow-hidden">
                      {portalSettings.logoUrl ? <img src={portalSettings.logoUrl} alt="Logo" className="w-full h-full object-cover" /> : "ESS"}
                    </div>
                    <div>
                      <h2 className="text-2xl sm:text-3xl font-black tracking-tight text-brand-950 uppercase font-heading">
                        {portalSettings.schoolName}
                      </h2>
                      <p className="text-xs font-bold text-slate-700 mt-0.5">
                        {portalSettings.address}
                      </p>
                      <p className="text-xs text-brand-800 font-semibold mt-0.5">
                        Website: emmanuelsecondaryschool.com | Tel: 07039009964, 07065166377
                      </p>
                    </div>
                  </div>

                  <div className="w-24 h-24 rounded-lg border-2 border-slate-300 overflow-hidden bg-slate-100 shrink-0 shadow-inner">
                    {foundStudent.passportUrl ? (
                      <img src={foundStudent.passportUrl} alt={foundStudent.name} className="w-full h-full object-cover" />
                    ) : (
                      <img 
                        src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${foundStudent.id}`} 
                        alt={foundStudent.name} 
                        className="w-full h-full object-cover" 
                      />
                    )}
                  </div>
                </div>

                <div className="mt-4 bg-amber-400 text-slate-950 py-1.5 px-4 text-center text-xs font-black uppercase tracking-wider rounded border border-amber-500">
                  {selectedTerm.toUpperCase()} TERMINAL PERFORMANCE REPORT SHEET — {selectedSessionYear} SESSION
                </div>
              </div>

              {/* STUDENT BIO INFORMATION TABLE */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs font-semibold">
                <table className="w-full border-collapse border border-slate-300">
                  <tbody>
                    <tr className="bg-slate-50">
                      <td className="p-2 border border-slate-300 text-slate-500 w-1/3">STUDENT NAME:</td>
                      <td className="p-2 border border-slate-300 text-slate-900 font-bold uppercase">{foundStudent.name}</td>
                    </tr>
                    <tr>
                      <td className="p-2 border border-slate-300 text-slate-500">ADMISSION NO:</td>
                      <td className="p-2 border border-slate-300 text-brand-900 font-mono font-bold">{foundStudent.id}</td>
                    </tr>
                    <tr className="bg-slate-50">
                      <td className="p-2 border border-slate-300 text-slate-500">CLASS:</td>
                      <td className="p-2 border border-slate-300 text-slate-900 font-bold">{foundStudent.class}</td>
                    </tr>
                  </tbody>
                </table>

                <table className="w-full border-collapse border border-slate-300">
                  <tbody>
                    <tr className="bg-slate-50">
                      <td className="p-2 border border-slate-300 text-slate-500 w-1/3">GENDER:</td>
                      <td className="p-2 border border-slate-300 text-slate-900 font-bold uppercase">{foundStudent.gender || "MALE"}</td>
                    </tr>
                    <tr>
                      <td className="p-2 border border-slate-300 text-slate-500">ACADEMIC SESSION:</td>
                      <td className="p-2 border border-slate-300 text-slate-900 font-bold">{selectedSessionYear} ({selectedTerm})</td>
                    </tr>
                    <tr className="bg-slate-50">
                      <td className="p-2 border border-slate-300 text-slate-500">ATTENDANCE:</td>
                      <td className="p-2 border border-slate-300 text-emerald-800 font-bold">122 DAYS OUT OF 125 DAYS</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              {/* SUBJECT SCORE ASSESSMENT TABLE */}
              <div className="overflow-x-auto">
                <table className="w-full border-collapse border border-slate-300 text-xs text-center">
                  <thead>
                    <tr className="bg-slate-900 text-white font-bold uppercase">
                      <th className="p-2.5 border border-slate-700 text-left w-48">Subject</th>
                      <th className="p-2.5 border border-slate-700 w-12">CA1 (10)</th>
                      <th className="p-2.5 border border-slate-700 w-12">CA2 (10)</th>
                      <th className="p-2.5 border border-slate-700 w-12">CA3 (10)</th>
                      <th className="p-2.5 border border-slate-700 w-12">CA4 (10)</th>
                      <th className="p-2.5 border border-slate-700 w-16 bg-slate-800">Total CA (40)</th>
                      <th className="p-2.5 border border-slate-700 w-16">Exam (60)</th>
                      <th className="p-2.5 border border-slate-700 w-20 bg-amber-950 text-amber-300 font-black">Total (100)</th>
                      <th className="p-2.5 border border-slate-700 w-16">Grade</th>
                      <th className="p-2.5 border border-slate-700 w-28">Remark</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-200">
                    {studentScores.length > 0 ? (
                      studentScores.map((sc) => {
                        const caTotal = (sc.ca1 || 0) + (sc.ca2 || 0) + (sc.ca3 || 0) + (sc.ca4 || 0);
                        return (
                          <tr key={sc.id} className="hover:bg-slate-50">
                            <td className="p-2.5 border border-slate-300 text-left font-bold text-slate-900">{sc.subject}</td>
                            <td className="p-2.5 border border-slate-300 text-slate-700">{sc.ca1 || "-"}</td>
                            <td className="p-2.5 border border-slate-300 text-slate-700">{sc.ca2 || "-"}</td>
                            <td className="p-2.5 border border-slate-300 text-slate-700">{sc.ca3 || "-"}</td>
                            <td className="p-2.5 border border-slate-300 text-slate-700">{sc.ca4 || "-"}</td>
                            <td className="p-2.5 border border-slate-300 font-semibold bg-slate-50 text-slate-900">{caTotal}</td>
                            <td className="p-2.5 border border-slate-300 font-semibold text-slate-900">{sc.exam}</td>
                            <td className="p-2.5 border border-slate-300 font-black text-emerald-800 text-sm bg-emerald-50/50">{sc.total}</td>
                            <td className="p-2.5 border border-slate-300 font-bold text-brand-900">{sc.grade}</td>
                            <td className="p-2.5 border border-slate-300 font-medium text-slate-700">{sc.remark}</td>
                          </tr>
                        );
                      })
                    ) : (
                      <tr>
                        <td colSpan={10} className="p-6 text-slate-500 font-medium">
                          No score records recorded for this term yet. Contact school examination officer.
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>

              {/* SUMMARY & REMARKS */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
                <div className="md:col-span-2 space-y-3">
                  <table className="w-full border-collapse border border-slate-300">
                    <tbody>
                      <tr className="bg-slate-100 font-bold">
                        <td className="p-2 border border-slate-300 w-1/2">TOTAL MARKS OBTAINED:</td>
                        <td className="p-2 border border-slate-300 text-emerald-800 text-sm font-black">{totalObtained} MARKS</td>
                      </tr>
                      <tr>
                        <td className="p-2 border border-slate-300 text-slate-600">OVERALL AVERAGE (%):</td>
                        <td className="p-2 border border-slate-300 text-slate-900 font-bold">{averagePercentage}% ({overallGrade})</td>
                      </tr>
                      <tr className="bg-slate-50">
                        <td className="p-2 border border-slate-300 text-slate-600">CLASS POSITION:</td>
                        <td className="p-2 border border-slate-300 text-brand-900 font-black">{studentScores[0]?.position || "1st"} OUT OF 32 STUDENTS</td>
                      </tr>
                    </tbody>
                  </table>

                  <div className="p-3 bg-slate-50 border border-slate-300 rounded-lg space-y-1">
                    <p className="font-bold text-slate-900">PRINCIPAL'S REMARK:</p>
                    <p className="text-slate-700 font-medium italic">
                      "An impressive academic performance with commendable diligence across all registered subjects. Keep aiming for highest distinction!"
                    </p>
                  </div>
                </div>

                {/* AFFECTIVE EVALUATION */}
                <div className="border border-slate-300 rounded-lg p-3 bg-slate-50 space-y-2">
                  <p className="font-bold text-slate-900 text-center border-b border-slate-300 pb-1 uppercase">AFFECTIVE DOMAIN</p>
                  <div className="space-y-1 text-[11px]">
                    <div className="flex justify-between border-b border-slate-200 py-0.5">
                      <span className="text-slate-600">Attentiveness:</span>
                      <span className="font-bold text-slate-900">5 / 5</span>
                    </div>
                    <div className="flex justify-between border-b border-slate-200 py-0.5">
                      <span className="text-slate-600">Neatness & Politeness:</span>
                      <span className="font-bold text-slate-900">5 / 5</span>
                    </div>
                    <div className="flex justify-between border-b border-slate-200 py-0.5">
                      <span className="text-slate-600">Punctuality:</span>
                      <span className="font-bold text-slate-900">4 / 5</span>
                    </div>
                    <div className="flex justify-between border-b border-slate-200 py-0.5">
                      <span className="text-slate-600">Honesty & Humility:</span>
                      <span className="font-bold text-slate-900">5 / 5</span>
                    </div>
                    <div className="flex justify-between py-0.5">
                      <span className="text-slate-600">Sports & Leadership:</span>
                      <span className="font-bold text-slate-900">4 / 5</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* FOOTER SIGNATURE & VERIFICATION */}
              <div className="pt-4 border-t border-slate-300 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs font-semibold">
                <div>
                  <p className="text-slate-500">NEXT TERM RESUMPTION:</p>
                  <p className="text-slate-900 font-bold">MONDAY, 14TH SEPTEMBER 2026</p>
                </div>

                <div className="text-center sm:text-right">
                  <p className="text-slate-500 uppercase">Principal's Signature & Stamp:</p>
                  {portalSettings.principalSignatureUrl && (
                    <div className="h-10 mt-1 flex justify-center sm:justify-end">
                      <img src={portalSettings.principalSignatureUrl} alt="Principal Signature" className="h-full object-contain" />
                    </div>
                  )}
                  <p className="text-slate-900 font-bold mt-1">{portalSettings.principalName || "MR. ZAGWA SAMUEL"}</p>
                </div>
              </div>

            </div>
          </div>
        )}

      </div>
    </div>
  );
}
